### ISSUE TITLE
Where Nijika?

### ISSUE THREAD

**Issue by TheGameratorT** [TigaTiga25/Lethal-Bocchi-Band-Suits#1]
I expected Nijika, not Bocchi.

![NIJIKA](https://i.ppy.sh/9fe4b46031fe45f179614801c9d704926e652ee0/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f313032373736303237313331393635303430352f313034393932303536373730323231323631382f32303232313230375f3030313634342e6a7067)

yellow

please make her now I need her

**Comment by TigaTiga25** [comment]
Bocchi ran away alone to the facility, so unfortunately no Nijika for now.

![](https://i.kym-cdn.com/photos/images/original/002/498/221/f18)

**Comment by TheGameratorT** [comment]
thank you for making nijik. 😃 

yellow

(she is uyellow)

**Comment by TigaTiga25** [comment]
no problem, enjoy yellow dorito 😋

yellow

(she is dorritos)
